import { useEffect, useState } from 'react'
import QRCode from 'qrcode'
import { cx } from './cx'
import { Spinner } from './Button'

export interface QrCodeProps {
  /** Payload to encode (e.g. a PromptPay payload). */
  text: string
  /** Width/height in px (default 240). Shrinks to fit narrow screens. */
  size?: number
  /** Accessible description, e.g. 'QR พร้อมเพย์ ฿250'. */
  label?: string
  className?: string
}

interface Rendered {
  text: string
  svg: string | null
  failed: boolean
}

/** QR code rendered as SVG (black on white, quiet zone 1, error correction M). */
export function QrCode({ text, size = 240, label = 'QR code', className }: QrCodeProps) {
  const [out, setOut] = useState<Rendered | null>(null)

  useEffect(() => {
    if (!text) return
    let alive = true
    QRCode.toString(text, { type: 'svg', margin: 1, errorCorrectionLevel: 'M' })
      .then((svg) => {
        if (alive) setOut({ text, svg, failed: false })
      })
      .catch((err: unknown) => {
        console.error('[ui] QR render failed', err)
        if (alive) setOut({ text, svg: null, failed: true })
      })
    return () => {
      alive = false
    }
  }, [text])

  const current = out && out.text === text ? out : null
  const failed = !text || current?.failed === true
  const style = { width: size }

  if (failed)
    return (
      <div className={cx('qr', 'qr-state', className)} style={style} role="img" aria-label="สร้าง QR ไม่ได้">
        สร้าง QR ไม่ได้
      </div>
    )
  if (!current?.svg)
    return (
      <div className={cx('qr', 'qr-state', className)} style={style}>
        <Spinner size={28} />
      </div>
    )
  return (
    <div
      className={cx('qr', className)}
      style={style}
      role="img"
      aria-label={label}
      // Generated by the qrcode library from module data only (the text is not embedded).
      dangerouslySetInnerHTML={{ __html: current.svg }}
    />
  )
}
